### ISSUE TITLE
[bug] JModelica doesn't compile the condition of an if-statement correctly

### ISSUE THREAD

**Issue by Foadsf** [modelon/PyFMI#19]
I'm not sure if it is a PyModelica or PyFMI bug, but considering that [the Jmodelica forum](https://jmodelica.org/forum) is still down, I'm gonna write here anyway. I was trying to solve my problem [here](https://stackoverflow.com/q/58227795/4999991) and followed by fixing some bugs [here](https://www.openmodelica.org/forum/default-topic/2794-openmodelica-doesn-t-follow-the-discrete-logic-as-expected), but then I realized there should be a bug in JModelica (i.e., PyModelica+PyFMI). Consider this versy simple model:

~~~
//test_1.mo
model test_1
  //parameters
  Real firstVar;
  Real secondVar;
  Real thirdVar;

algorithm
  firstVar := 1.0 * sin(time);
  secondVar := abs(firstVar);
  if (firstVar < secondVar) then
    thirdVar := 1;
  else
    thirdVar := -1;
  end if;
  
end test_1;
~~~

and the Python sode:

~~~python
import matplotlib.pylab as plt

from pymodelica import compile_fmu
from pyfmi import load_fmu

model_name = 'test_1'
mofile = 'test_1.mo'

fmu_name = compile_fmu(model_name, mofile)
sim = load_fmu(fmu_name)

opts = sim.simulate_options()
opts["ncp"] = 500
opts['CVode_options']['rtol'] = 1.0e-8
res = sim.simulate(final_time=10, options=opts)

time = res['time']
firstVar = res['firstVar']
secondVar = res['secondVar']
thirdVar = res['thirdVar']

plt.plot(time, firstVar, label="firstVar")
plt.plot(time, secondVar, label="secondVar")
plt.plot(time, thirdVar, label="thirdVar")
plt.legend()
plt.show()
~~~

which result in

![plot2](https://user-images.githubusercontent.com/12762442/66205400-9bda0c80-e6ad-11e9-8993-deab920fa4d4.png)

as you may see at point 1 the `thirdVar` doesn't return to `-1` as it is expected by the if-statement. 

**P.S.** OpenModelica also has the same bug as I reported [here](https://openmodelica.org/forum/default-topic/2795-bug-condition-of-an-if-statement-in-an-algorithm)!

**Comment by chria** [comment]
This is not the right forum for JModelica issues. 

This is however not an issue with JModelica. The issue is with the settings to the solver. The problem is too "simple" for the solver which means that the solver will take very large steps (and still meet the tolerance requirement). This also results in that events are skipped because the solver jumps over them. This is a general issue for all solvers and what a users needs to do is to set an appropriate maximum step-size to the solver. 

So what you need to do is to set the maximum step-size
`opts = model.simulate_options();
opts["CVode_options"]["maxh"] = ...`

**Comment by Foadsf** [comment]
@chria thanks for the reply. How can I identify that if the issues I have, is with JModelica, PyModelica or PyFMI?

**Comment by chria** [comment]
Looking at this title indicates a JModelica issue and thus it should not be here.

Regarding the issue, there is no bug as I mentioned in my previous comment.
